version: "3.7"
services:
  elasticsearch:
    image: docker.ub.gu.se/koha-elasticsearch:${REVISION}
    ports:
      - "${HOST_PORT}:9200"
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    volumes:
      - ${DATA_PATH}:/usr/share/elasticsearch/data
    restart: always

